language: python

python:
  - 2.7
  - pypy

env:
  - "FOO=bar"
  - "FOO=$(echo dollar paren)"
  - "FOO=`echo backtick`"

install:
  - echo "Foo=${FOO}"
  - pip install coveralls coverage
  - python setup.py --version
  - pip install -e.

script:
  - coverage run --branch --source machinist $(type -p trial) machinist
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
